config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :item_lists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root"item_lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item_list.rb
class ItemList < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates_presence_of :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :item_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/item_lists_controller.rb
class ItemListsController < ApplicationController
  before_action :set_item_list, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /item_lists
  # GET /item_lists.json
  def index
    @item_lists = ItemList.all
  end

  # GET /item_lists/1
  # GET /item_lists/1.json
  def show
  end

  # GET /item_lists/new
  def new
    @item_list = ItemList.new
  end

  # GET /item_lists/1/edit
  def edit
  end

  # POST /item_lists
  # POST /item_lists.json
  def create
    @item_list = ItemList.new(item_list_params)
    @item_list.user_id = current_user.id

    respond_to do |format|
      if @item_list.save
        format.html { redirect_to @item_list, notice: 'Item list was successfully created.' }
        format.json { render :show, status: :created, location: @item_list }
      else
        format.html { render :new }
        format.json { render json: @item_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_lists/1
  # PATCH/PUT /item_lists/1.json
  def update
    respond_to do |format|
      if @item_list.update(item_list_params)
        format.html { redirect_to @item_list, notice: 'Item list was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_list }
      else
        format.html { render :edit }
        format.json { render json: @item_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_lists/1
  # DELETE /item_lists/1.json
  def destroy
    @item_list.destroy
    respond_to do |format|
      format.html { redirect_to item_lists_url, notice: 'Item list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_list
      @item_list = ItemList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_list_params
      params.require(:item_list).permit(:title, :description, :expected_cost, :image, :contact)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_lists_helper.rb
module ItemListsHelper
end

app/views/item_lists/_form.html.erb
<%= form_with(model: @item_list, local: true) do |form| %>
  <% if @item_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_list.errors.count, "error") %> prohibited this item_list from being saved:</h2>

      <ul>
      <% @item_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :expected_cost %>
    <%= form.number_field :expected_cost %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
    <% if form.object.image? %>
      <%= image_tag form.object.image_url(:thumb) %>
      <%= form.label :remove_image %>
      <%= form.check_box :remove_image %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :contact %>
    <%= form.text_area :contact %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/item_lists/edit.html.erb
<h1>Editing Item List</h1>

<%= render 'form', item_list: @item_list %>

<%= link_to 'Show', @item_list %> |
<%= link_to 'Back', item_lists_path %>

app/views/item_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Item Lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Expected cost</th>
      <th>Image</th>
      <th>Contact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_lists.each do |item_list| %>
      <tr>
        <td><%= item_list.title %></td>
        <td><%= item_list.description %></td>
        <td><%= item_list.expected_cost %></td>
        <td><%= image_tag item_list.image_url(:thumb) %></td>
        <td><%= item_list.contact %></td>
        <td><%= link_to 'Show', item_list %></td>
        <%  if item_list.user_id == current_user.id %>
        <td><%= link_to 'Edit', edit_item_list_path(item_list) %></td>
        <td><%= link_to 'Destroy', item_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item List', new_item_list_path %>

app/views/item_lists/new.html.erb
<h1>New Item List</h1>

<%= render 'form', item_list: @item_list %>

<%= link_to 'Back', item_lists_path %>

app/views/item_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item_list.description %>
</p>

<p>
  <strong>Expected cost:</strong>
  <%= @item_list.expected_cost %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @item_list.image_url(:thumb) %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @item_list.contact %>
</p>

<%  if @item_list.user_id == current_user.id %>
<%= link_to 'Edit', edit_item_list_path(@item_list) %> |
  <% end %>
<%= link_to 'Back', item_lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Itemlist</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Welcome NITK Students", '#', id: "logo" %><br>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path , class: "btn "%></li>
        <% if user_signed_in? %>
          <li><%= link_to "Account", edit_user_registration_path, class: "btn "  %></li>
          <li>
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "btn " %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "btn " %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
<div class="container">
  <%= yield %>
</div>
</body>
</html>